### ISSUE TITLE
TypeError: cannot serialize '_io.BufferedReader' object

### ISSUE THREAD

**Issue by bashu** [saulshanabrook/django-dumper#32]
Hey,

Got this using https://github.com/niwinz/django-redis as backend

``` python
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 233, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/dumper/middleware.py", line 47, in process_response
    dumper.utils.cache.set(key, response)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django_redis/cache.py", line 66, in set
    return self.client.set(*args, **kwargs)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django_redis/client/default.py", line 117, in set
    nvalue = self.encode(value)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django_redis/client/default.py", line 313, in encode
    encoded_value = self._serializer.dumps(value)
  File "/home/vagrant/.virtualenv/lib/python3.4/site-packages/django_redis/serializers/pickle.py", line 40, in dumps
    return pickle.dumps(value, self._pickle_version)
TypeError: cannot serialize '_io.BufferedReader' object
```

related settings:

``` python
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', '127.0.0.1:6379'),
        'TIMEOUT': 60 * 60,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
}
```

**Comment by bashu** [comment]
nevermind, forgot to add:

``` python
DUMPER_PATH_IGNORE_REGEX = r'^/(?:(?:admin)|(?:static)|(?:media))/'
```
